### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by zhmurko-anastasi**
Add final changes to the master-branch

### CODE REVIEW

**Comment by tfetisova** [comment]
Final code reviewed.

**Comment by zhmurko-anastasi** [comment]
Agree to merge

**Review by tfetisova — APPROVED** [review]
All final changes already discussed

**Review by zhmurko-anastasi — COMMENTED** [review]
Approved !

**Review by OlgaVakulenko — CHANGES_REQUESTED** [review]
Already discussed

**Review by zhmurko-anastasi — COMMENTED** [review]
Approved

**Review by OlgaVakulenko — APPROVED** [review]

**Pull request merged**
